version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "6401:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
      - postgres-data:/data/postgres
  stats:
    build: ./stats
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - postgres
volumes:
  postgres-data:
